apiVersion: v1
kind: Pod
metadata:
  name: my-pod-lb
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadblancer-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: my-pod-lb
