apiVersion: v1
kind: Pod
metadata:
  app: my-pod-np
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: my-pod-np
