apiVersion: v1
kind: pod
metadata:
  name: my-pod-cip
spec:
  selector:
    metadata:
      app: my-pod-cip
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-pod-cip
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: my-pod-cip
